version: "3.9"
services:
  reactapp:
    container_name: reactapp
    restart: always
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - nodeapi

  nodeapi:
    container_name: nodeapi
    restart: always
    build:
      context: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
